### ISSUE TITLE
images appear as "corrupted" on windows

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/book.mso4sc.eu#13]
Images can not be readed on Windows. I think is a CRLF issue.

**Comment by gdolle** [comment]
@emepetres Is it on the book.mso4sc.cemosis.fr website or when you generate in local ?

**Comment by emepetres** [comment]
It is when you clone the repository in a windows machine.

**Comment by gdolle** [comment]
Ah! I think you have to install git-lfs.
https://git-lfs.github.com/
Images are stored on Github LFS (In fact you might have just the symlink)
