### ISSUE TITLE
Review deliverables docx conversion

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/book.mso4sc.eu#15]
This issue is related to #14 

- We should check/review that links, images, tables are printed properly compared to original docx
- Check each deliverables are at final version.

- [x] D2.1   @gdolle
- [x] D2.2   @gdolle
- [x] D2.3   @gdolle
- [x] D2.4   @gdolle
- [x] D2.5   @gdolle
- [x] D3.1   @gdolle   
- [x] D3.2   @gdolle
- [x] D4.1   @gdolle
- [x] D4.2
- [x] D5.1   @gdolle
- [x] D5.2   @gdolle
- [x] D6.1   @gdolle

PS: We should not anymore put draft version in the book (We will forget to update it otherwise).

PS: **Help for debug and fix title (first time check only)**:
-  **Table:** For vi user. After docx conversion, some wrong `---` are added in table to fix it
`ggvG` then `:` and write `s/|\n_*\n\(.*\)\n_*/|\1/c`   (remove --- and replace inner occurence)
- **Title:** look for title looking like `/1..*\n=`. and remove `1. `.

**Comment by gdolle** [comment]
@jbwahl I propose that you do the second check after me if you are ok with that ? I'll put my name in the issue describtion each time I finish to review/edit (To avoid double work).

**Comment by gdolle** [comment]
@prudhomm @jbwahl I'm done. All deliverables are updated to last version + table check + title check.
Let me know if you see format problems.

**Comment by jbwahl** [comment]
thx @gdolle. Sry for my non contribution, i'm waiting for my owncloud account. 
I'll recheck all this on monday.

**Comment by gdolle** [comment]
Yep don't worry it was fast so I thought easier to do it in one go. Just do a second check to see if there're problems ;)

**Comment by jbwahl** [comment]
@gdolle i pushed d4.2 and reviewed the others.
Can you double check d4.2 plz ?

**Comment by gdolle** [comment]
@jbwahl Yes I'll have a look

**Comment by gdolle** [comment]
@jbwahl Ok we are done.
