### ISSUE TITLE
Feel++ does not render correctly in nav.adoc

### ISSUE THREAD

**Issue by johanjan** [MSO4SC/book.mso4sc.eu#31]
In:

http://book.mso4sc.cemosis.fr/madfs/0.1/fenics/README/

Feel++ render as:

feelpp:index.adoc

instead of the expected:

Feel++

This appears to be a bug in https://github.com/MSO4SC/book.mso4sc.eu/blob/master/docs/madfs/modules/ROOT/nav.adoc

**Comment by prudhomm** [comment]
Hum weird. I will look into that. thanks!

**Comment by prudhomm** [comment]
@johanjan this is now fixed here
http://book.mso4sc.cemosis.fr/madfs/latest/

there is no version anymore but rather `latest`
